Issue 47 2
tsudo42/minishell pull request #51
Opened 2022-09-16 07:53 UTC by hosuzuki

builtin sort is fixed

2022-09-16 10:04 UTC, tsudo42 requested changes
### segv
`ft_lstnew` のNULLチェック（malloc）をお願いします！

### algo
一番最後のvarが表示されません。

### leak
`ft_lstclear(&list_head, NULL);` だと思います！

2022-09-16 13:08 UTC, hosuzuki commented
レビューありがとうございます！
segvとleaksは完全に間違ってました。。ありがとうございます。

algoですが、一番最後のvarの表示とは何のことでしょうか？
'export'を入力後に表示される環境変数の一番最後は、bashで出力すると同じものが表示されています。

2022-09-17 02:15 UTC, tsudo42 commented
一番最後のvarとは、元のenvvarで、最も最後に追加された変数です。
`init_list`内の
```C
	var = env->vars;
	list = ft_lstnew(var);
	if (var->next != NULL)
		var = var->next;
	while (var->next != NULL)
	{
		ft_lstadd_back(&list, ft_lstnew(var));
		var = var->next;
	}
```
の辺りで、`->next`がNULLな`var`が追加されないと思います！

2022-09-17 10:20 UTC, hosuzuki commented
ご返信ありがとうございます！
大変失礼いたしました！そういうことですね。exportコマンドを入力すれば、ソートされるので、末尾に表示されるのは、そもそもvarの末尾のものとは別ものでした。

すべて修正完了しておりますので、恐れ入りますが、お手すきのときに再度ご確認いただけるとありがたいです。

2022-09-18 06:20 UTC, tsudo42 approved these changes

2022-09-18 06:21 UTC, merged